//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public int cantidad { get; set; }
        public decimal costo { get; set; }
        public int subcontrata_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int created_by { get; set; }
        public int updated_by { get; set; }
    
        public virtual Subcontrata Subcontrata { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
